# Generated by Django 4.1.7 on 2023-07-01 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='paper'),
            preserve_default=False,
        ),
    ]
