# Generated by Django 4.1.7 on 2023-07-04 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_paper_date_paper_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='date',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='file',
        ),
    ]
