# Generated by Django 4.1.7 on 2023-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_alter_paper_link_alter_paper_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file2',
            field=models.FileField(default=1, upload_to='sac'),
            preserve_default=False,
        ),
    ]
